spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/prismabooking
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate:
        format_sql: true
---
spring:
  config:
    activate:
      on-profile: dev, default

prisma-booking:
  default-page-size-limit: 10
  max-page-size-limit: 10000

server:
  port: 8081
---
spring:
  config:
    activate:
      on-profile: staging

prisma-booking:
  default-page-size-limit: 10
  max-page-size-limit: 100

server:
  port: 8081
---
spring:
  config:
    activate:
      on-profile: prod

prisma-booking:
  default-page-size-limit: 10
  max-page-size-limit: 100

server:
  port: 8080